# Site settings
title: Andre Simpelo's Portfolio
email: dresimpelo
url: https://example.github.io
baseurl: ""
description: "Andre Simpelo's Project Portfolio"
keywords: "deep learning,machine learning,ai,artificial intelligence,self driving cars,robotics,guitar,jazz"
meta_author: Simpelo Andre
hello: Hi, my name is
name: Andre Simpelo
skills: "Programmer, Hacker, Deep Learning Enthusiast"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
# Footer settings
footer:
  title: ""
  email: "Contact: dresimpelo [at] gmail [dot] com"
  thanks: Thanks for dropping by!
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/DreSimpelo
  - title: linkedin
    url: https://www.linkedin.com/in/DreSimpelo
  - title: soundcloud
    url: https://soundcloud.com/DreSimpelo
  - title: github
    url: https://github.com/DreSimpelo
# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge